map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "map.yaml"

amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    global_frame_id: "map"
    laser_model_type: "likelihood_field"
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25

bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "/odom"

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: -0.3
      max_vel_x: 0.3
      min_vel_y: -0.3
      max_vel_y: 0.3
      min_vel_theta: -0.3
      max_vel_theta: 0.3
      acc_lim_x: 0.3
      acc_lim_y: 0.3
      acc_lim_theta: 0.3
      decel_lim_x: 0.3
      decel_lim_y: 0.3
      decel_lim_theta: 0.3
      vx_samples: 20
      vy_samples: 20
      vtheta_samples: 20
      sim_time: 1.7
      sim_granularity: 0.025
      angular_sim_granularity: 0.025
      transform_tolerance: 0.1
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      prune_plan: true
      short_circuit_trajectory_evaluation: true
      critics: ["GoalDist", "PathDist", "PathAlign", "GoalAlign", "ObstacleFootprintCritic", "PreferForwardCritic"]
      GoalDist.scale: 1.0
      PathDist.scale: 1.0
      PathAlign.scale: 1.0
      GoalAlign.scale: 1.0
      ObstacleFootprintCritic.scale: 1.0
      PreferForwardCritic.scale: 1.0

planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

recoveries_server:
  ros__parameters:
    use_sim_time: false
    costmap_topic: "local_costmap/costmap_raw"
    footprint_topic: "local_costmap/published_footprint"
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      publish_frequency: 2.0
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 5.0
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      inflation_layer:
        enabled: true
        inflation_radius: 0.55
      obstacle_layer:
        enabled: true
        observation_sources: scan
        scan:
          data_type: "LaserScan"
          topic: scan
          marking: true
          clearing: true

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      publish_frequency: 1.0
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 1.0
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      inflation_layer:
        enabled: true
        inflation_radius: 0.55
      obstacle_layer:
        enabled: true
        observation_sources: scan
        scan:
          data_type: "LaserScan"
          topic: scan
          marking: true
          clearing: true 
