### ekf config file ###
ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        sensor_timeout: 0.1
        two_d_mode: true
        publish_tf: true
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        odom0: odom
        odom0_config: [true,  true,  false,
                      false, false, false,
                      true,  true,  false,
                      false, false, false,
                      false, false, false]
        odom0_queue_size: 10
        odom0_nodelay: true
        odom0_differential: false
        odom0_relative: false

        imu0: /camera/imu
        imu0_config: [false, false, false,
                     true,  true,  true,
                     false, false, false,
                     true,  true,  true,
                     true,  true,  true]
        imu0_nodelay: true
        imu0_differential: false
        imu0_relative: false
        imu0_queue_size: 10

        process_noise_covariance: [0.005, 0,    0,    0,    0,     0,     0,     0,     0,    0,     0,     0,    0,    0,    0,
                                 0,    0.005, 0,    0,    0,     0,     0,     0,     0,    0,     0,     0,    0,    0,    0,
                                 0,    0,    0.006, 0,    0,     0,     0,     0,     0,    0,     0,     0,    0,    0,    0,
                                 0,    0,    0,    0.001, 0,     0,     0,     0,     0,    0,     0,     0,    0,    0,    0,
                                 0,    0,    0,    0,    0.001, 0,     0,     0,     0,    0,     0,     0,    0,    0,    0,
                                 0,    0,    0,    0,    0,     0.001, 0,     0,     0,    0,     0,     0,    0,    0,    0,
                                 0,    0,    0,    0,    0,     0,     0.025, 0,     0,    0,     0,     0,    0,    0,    0,
                                 0,    0,    0,    0,    0,     0,     0,     0.025, 0,    0,     0,     0,    0,    0,    0,
                                 0,    0,    0,    0,    0,     0,     0,     0,     0.04, 0,     0,     0,    0,    0,    0,
                                 0,    0,    0,    0,    0,     0,     0,     0,     0,    0.01,  0,     0,    0,    0,    0,
                                 0,    0,    0,    0,    0,     0,     0,     0,     0,    0,     0.01,  0,    0,    0,    0,
                                 0,    0,    0,    0,    0,     0,     0,     0,     0,    0,     0,     0.02, 0,    0,    0,
                                 0,    0,    0,    0,    0,     0,     0,     0,     0,    0,     0,     0,    0.01, 0,    0,
                                 0,    0,    0,    0,    0,     0,     0,     0,     0,    0,     0,     0,    0,    0.01, 0,
                                 0,    0,    0,    0,    0,     0,     0,     0,     0,    0,     0,     0,    0,    0,    0.015]

        initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,     0,     0,     0,     0,     0,     0,     0,     0,    0,
                                    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,     0,     0,     0,     0,     0,    0,
                                    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,     0,     0,     0,     0,     0,    0,
                                    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,     0,     0,     0,     0,     0,    0,
                                    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,     0,     0,     0,     0,     0,    0,
                                    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,     0,     0,     0,     0,    0,
                                    0,    0,    0,    0,    0,    0,     1e-9, 0,     0,     0,     0,     0,     0,     0,    0,
                                    0,    0,    0,    0,    0,    0,     0,     1e-9, 0,     0,     0,     0,     0,     0,    0,
                                    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,     0,     0,     0,     0,    0,
                                    0,    0,    0,    0,    0,    0,     0,     0,     0,     1e-9, 0,     0,     0,     0,    0,
                                    0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     1e-9, 0,     0,     0,    0,
                                    0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     0,     1e-9, 0,     0,    0,
                                    0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     0,     0,     1e-9, 0,    0,
                                    0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     0,     0,     0,     1e-9, 0,
                                    0,    0,    0,    0,    0,    0,     0,     0,     0,     0,     0,     0,     0,     0,    1e-9] 