amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.1
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    num_bt_iterations: 1
    default_enable_service: true
    default_max_skips: 0
    goal_status_topic: /navigate_to_pose/_action/feedback
    goal_topic: /goal_pose
    path_topic: /plan
    robot_bt_executor_type: "bt_navigator:NavigateToPose"
    robot_bt_plugin: "NavigateToPose"
    robot_bt_plugin_filename: "bt_navigator"
    robot_bt_plugin_package: "nav2_bt_navigator"
    robot_initial_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    robot_use_available_plugins: true
    server_timeout: 20
    use_goal_reached_condition: true
    wait_for_service_timeout: 20

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.5
      max_vel_y: 0.0
      max_vel_trans: 0.5
      min_speed_xy: 0.1
      max_speed_xy: 0.5
      min_speed_theta: 0.3
      acc_lim_x: 0.2
      acc_lim_y: 0.0
      acc_lim_theta: 0.2
      decel_lim_x: 0.2
      decel_lim_y: 0.0
      decel_lim_theta: 0.2
      min_vel_theta: -0.3
      max_vel_theta: 0.3
      acc_lim: 0.2
      min_speed: 0.1
      max_speed: 0.5
      min_turning_radius: 0.4
      max_turning_radius: 0.9
      goal_dist_tol: 0.5
      goal_heading_tol: 0.25
      goal_time_tol: 0.0
      debug_trajectory_details: true
      short_collision_cost_scale: 3.0
      long_collision_cost_scale: 1.0
      max_linear_accel: 2.0
      max_lineardecl: 2.5
      max_ang_accel: 3.0
      max_ang_decel: 3.0
      min_obstacle_dist: 0.5
      buffer_dist: 0.5
      base_obstacle_dist: 0.5
      scaling_speed: 0.25
      max_scaling_factor: 0.2
      use_rotate_to_heading_angular_velocity_scaling: true
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "PathFollow", "GoalDist"]
      BaseObstacle.scale: 0.02
      BaseObstacle.max_obstacle_dist: 2.0
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      GoalAlign.min_angle_tolerance: 0.10
      GoalAlign.max_angle_tolerance: 0.785
      GoalAlign.xy_goal_tolerance: 0.25
      GoalDist.scale: 32.0
      Oscillation.scale: 0.0
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      PathAlign.min_angle_tolerance: 0.10
      PathAlign.max_angle_tolerance: 0.785
      PathDist.scale: 32.0
      PathFollow.scale: 32.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factors: "gave_up"
      RotateToGoal.min_angle_tolerance: 0.10
      RotateToGoal.max_angle_tolerance: 0.785
      RotateToGoal.xy_goal_tolerance: 0.25
      RotateToGoal.lookahead_time: -1.0
      RotateToGoal.trans_stopped_velocity: 0.25
      RotateToGoal.shortest_dist: true

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0

    # Goal checker parameters
    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true
      goal_heading_tol: 0.25
      goal_xy_tol: 0.25
      goal_time_tol: 10.0
      use_check_obstacle: true
      max_obstacle_dist: 0.5
      max_obstacle_height: 0.6
      min_obstacle_dist: 0.25
      min_obstacle_height: 0.0
      transform_tolerance: 0.2
      global_frame: map
      robot_base_frame: base_link
      use_velocity_check: false
      velocity_check_tol: 0.25
      velocity_check_period: 9.0
      stateful: true

costmap_2d:
  ros__parameters:
    use_sim_time: False
    update_frequency: 1.0
    publish_frequency: 0.0
    global_frame: map
    robot_base_frame: base_link
    use_maximum: false
    rolling_window: true
    width: 3
    height: 3
    resolution: 0.05
    track_unknown_space: true
    plugins: ["voxel_layer", "inflation_layer"]

    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      enabled: True
      publish_voxel_map: True
      origin_z: 0.0
      z_resolution: 0.05
      z_voxels: 16
      max_obstacle_height: 2.0
      mark_threshold: 1
      observation_sources: scan
      scan:
        sensor_frame: base_link
        data_type: "LaserScan"
        topic: /scan
        marking: true
        clearing: true
        min_obstacle_height: 0.0
        max_obstacle_height: 2.0
        min_obstacle_range: 0.3
        max_obstacle_range: 2.0
        raytrace_max_range: 2.0
        raytrace_min_range: 0.3
        obstacle_range: 2.0
        mark_threshold: 1
        clearing: true
        marking: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      cost_scaling_factor: 3.0
      inflation_radius: 0.55
      enabled: True

planner_server:
  ros__parameters:
    use_sim_time: False
    expected_planner_frequency: 20.0
    use_astar: false
    allow_unknown: true
    max_iterations: 100000
    max_planning_time: 4.0
    debug_logging: false
    tolerance: 0.5
    use_grid: true
    use_quadratic: true
    use_dijkstra: false
    use_gradient: true
    use_straight_line: false
    use_final_approach_orientation: true
    allow_primitive_interruption: true
    use_potential_heuristic: true
    use_orientation: true
    use_cell_weights: false
    lethal_cost: 253
    neutral_cost: 50
    cost_factor: 3.0
    publish_potential: true
    orientation_mode: 0
    orientation_window_size: 1
    planner_plugin: "GridBased"
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true
      planner_plugin: "GridBased"
      use_dijkstra: false
      use_quadratic: true
      use_grid: true
      use_orientation: true
      use_cell_weights: false
      lethal_cost: 253
      neutral_cost: 50
      cost_factor: 3.0
      publish_potential: true
      orientation_mode: 0
      orientation_window_size: 1

recovery_server:
  ros__parameters:
    use_sim_time: False
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 1.0
    recovery_plugins: ["spin", "backup", "get_path", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
      speed: 1.0
      time_allowance: 10.0
    backup:
      plugin: "nav2_recoveries/BackUp"
      speed: 0.1
      time_allowance: 10.0
      max_backup_time: 2.0
    wait:
      plugin: "nav2_recoveries/Wait"
      time_allowance: 10.0
    get_path:
      plugin: "nav2_recoveries/GetPath"
      goals: [[0.0, 0.0, 0.0], [0.0, 0.0, 3.14159]]
      goal_tolerances: [[0.25, 0.25, 0.25], [0.25, 0.25, 0.25]]
      cycles: 1
      goal_blackboard_id: "goal"
      path_blackboard_id: "path"
      use_start: false
      max_retries: 1
      max_time: 10.0
      backtrack: false

smoother_server:
  ros__parameters:
    use_sim_time: False
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    odom_topic: /odom
    map_topic: /map
    global_frame: map
    robot_base_frame: base_link
    transform_timeout: 0.2
    smoother_plugins: ["smoother"]
    smoother:
      plugin: "nav2_smoother/Smoother"
      max_curvature: 1.0
      speed: 0.2
      lookahead_time: 1.0
      transform_timeout: 0.2
      max_lookahead_dist: 0.9
      debug_only: false
      smoothing_duration: 2.0
      min_in_place_vel_theta: 0.1
      max_curvature: 1.0
      speed: 0.2
      lookahead_time: 1.0
      transform_timeout: 0.2
      max_lookahead_dist: 0.9
      debug_only: false
      smoothing_duration: 2.0
      min_in_place_vel_theta: 0.1 