costmap_filter_info_server:
  ros__parameters:
    type: 1  # Keepout filter
    mask_topic: "/dump_keepout_mask"
    base: 0.0
    multiplier: 1.0
    filter_info_topic: "/costmap_filter_info"
    mask_path: "package://moonpie_osamu/config/dump_keepout_mask.pgm"
    mask_origin: [4.38, 0.25, 0.0]
    mask_resolution: 0.05 