bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    default_bt_xml_filename: "navigate_to_pose_w_replanning_and_recovery.xml"
    tick_rate: 20.0

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    controller_plugins: ["FollowPath"]
    current_goal_checker: "SimpleGoalChecker"
    goal_checker_plugins: ["SimpleGoalChecker"]
    SimpleGoalChecker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_time_to_collision: 0.5
      max_time_to_collision: 1.0
      min_obstacle_dist: 0.5
      max_obstacle_dist: 2.0
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "PathAlign", "PathDist", "GoalAlign"]
      PathAlign.scale: 32.0
      PathDist.scale: 32.0
      GoalAlign.scale: 24.0
      RotateToGoal.scale: 32.0
      BaseObstacle.scale: 0.02
      Oscillation.scale: 0.01
      transform_tolerance: 0.5
      action_server_result_timeout: 20.0
      action_server_wait_timeout: 10.0

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      allow_unknown: true
      visualize_potential: true
      use_astar: false
      use_dijkstra: true
      use_grid: true
      use_quadratic: true
      use_old_navfn_behavior: false
      lethal_cost: 253
      neutral_cost: 50
      cost_scale: 3.0
      publish_potential: true
      orientation_mode: 0
      orientation_window_size: 1

behavior_server:
  ros__parameters:
    use_sim_time: false
    local_costmap:
      robot_radius: 0.22
      track_unknown_space: true
      always_send_full_costmap: true
      unknown_cost_value: 255
      lethal_cost_threshold: 253
      unknown_threshold: 15
      obstacle_range: 2.5
      raytrace_range: 3.0
      transform_tolerance: 0.5
      update_frequency: 2.0
      publish_frequency: 1.0
      static_map: false
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
    global_costmap:
      robot_radius: 0.22
      track_unknown_space: true
      always_send_full_costmap: true
      unknown_cost_value: 255
      lethal_cost_threshold: 253
      unknown_threshold: 15
      obstacle_range: 2.5
      raytrace_range: 3.0
      transform_tolerance: 0.5
      update_frequency: 0.5
      publish_frequency: 0.2
      static_map: false
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55 